### ISSUE TITLE
[htcvive] support hand controllers

### ISSUE THREAD

**Issue by grrrwaaa** [worldmaking/Max_Worldmaking_Package#2]

**Comment by kcoul** [comment]
Ought to leave open until consensus we have "complete support". i.e., there appears to be internal API recognition of D-Pad button presses on the touch-circle, saving the user the need to evaluate X/Y values at button_pressed time.

**Comment by grrrwaaa** [comment]
Not sure we want to put d-pad presses into the external; different apps are dividing the touchpad in different ways (into two, four, six, eight, etc. regions, some with a central region, etc.); strikes me as something better handled by users in Max. I guess we could give an example patcher, doing the cartopol conversion etc. 

Would be great to add a tilt-brush style example, eh?
