### ISSUE TITLE
[htcvive] add support for Vive Trackers

### ISSUE THREAD

**Issue by matcham** [worldmaking/Max_Worldmaking_Package#20]
please consider adding support for the brand new Vive Trackers !

**Comment by hectorC** [comment]
Related to this, I'm trying to use the Vive's controllers without the HMD connected. I already got one controller to work using a re-flashed Steam Dongle (tested with a Python script) but the [htcvive] Max object won't start or poll for controller data unless the HMD is plugged. I believe this would also allow the use of Vive Trackers without HMD.

**Comment by kcoul** [comment]
@hectorC feel free to create a new issue, the implementation of the solution is pretty different for what you're describing. I've also seen other situations where it was desirable to be up and running with only one controller and not the other - ideally you can mix and match any combination of hardware as needed.

@matcham feel free to reassign to me as I committed on the Cycling '74 forum to implementing this - I have a lot to gain from adding support as well, so it was worth ordering one.

**Comment by kcoul** [comment]
Works well enough to call this closed. A future enhancement will push tracker data to its own outlet, and on the Help file side, will dynamically separate up to 11 tracker streams by adding a wildcard for the serial number suffix.
