### ISSUE TITLE
Error 126 loading external htcvive

### ISSUE THREAD

**Issue by nanocat-net** [worldmaking/Max_Worldmaking_Package#23]
Hi,

I'm running Windows 10 Home with all current updates, and Max 7.3.4. I just downloaded the current version of the Worldmaking package and extracted it into my User library folder.

I have an HTC Vive and all of the required bits from Steam installed; the Vive works fine on this machine with Unity and with various Steam games.

I get an "Error 126 loading external htcvive" in my Max Console when adding an htcvive object to my patch.

I noticed in your instructions that a pre-requisite is the Visual Basic C++ Redistributable 2015; the link provided is outdated (I found it instead under https://www.microsoft.com/en-in/download/details.aspx?id=52685) - but as I've got a later version already installed, it won't install the 2015 version.

I'm not sure where to start debugging this - if you can give me a tip or a push in the right direction, I can provide more information.

Nick!

**Comment by grrrwaaa** [comment]
Hi Nick,

There shouldn't be any problem installing the Microsoft Visual C++ 2015 Redistributable library -- they are designed to be able to be install different versions (2013, 2015, 2017 etc.) side by side.

Did you put the entire package inside your My Documents/Max 7/Packages/ folder?

Oh wait -- it looks like @kcoul updated the project to VS2017 a month ago -- in which case you might need to 2017 redistributable; maybe this one: https://www.visualstudio.com/downloads/#microsoft-visual-c-redistributable-for-visual-studio-2017

I'll try to find a moment to roll those projects back to 2015, but I'm in a crush at the moment.

Graham

**Comment by nanocat-net** [comment]
Hey Graham!

I installed the 2017 redistributable, but I'm still getting the same "Error 126 loading external htcvive".

So then I moved the folder containing the package out of my "Library" folder, where I put it by mistake, and into the "Packages" folder.

Now it works.

I'll see myself out.

Sorry for troubling you on a Monday :-)

Nick
