### ISSUE TITLE
Forward WebSockets to another host/ip address

### ISSUE THREAD

**Issue by wprimett** [worldmaking/Max_Worldmaking_Package#24]
Hello,
So far, I've been successful in forwarding JSON strings to a webpage using the default localhost/127.0.0.1 ip. I see you can change the port number from MAX/MSP, but is it possbile to change the destination IP to something else.

Cheers,
William

**Comment by grrrwaaa** [comment]
Hi,

Not sure I fully understood. You can use the [ws.client] external to talk to websocket servers on specific IPs, if that helps. Messages will go to the external server and replies received will come out the outlet. 

The [ws] object is a local server. Other machines can access it via your machine's IP (on a LAN, or internet if your IP is public). Messages to [ws] will go to all connected clients. 

Graham

**Comment by wprimett** [comment]
Thanks for the swift response! Ah yes, you're explanation makes perfect sense. I was under the impression that you would need to specify a host upon send messages (like with OSC)

One thing I'm having trouble with however, is dynamically changing the port number from outside of the object. Where shooting "port" messages into the object, it successfully updates in the attribute menu. However, it doesn't take any effect and the receiver cannot respond on the given port.

[https://i.ibb.co/0Y02d7b/Screen-Shot-2019-03-14-at-6-59-27-PM.png](https://i.ibb.co/0Y02d7b/Screen-Shot-2019-03-14-at-6-59-27-PM.png)

[https://i.ibb.co/RvFHmMh/Screen-Shot-2019-03-14-at-7-11-09-PM.png](https://i.ibb.co/RvFHmMh/Screen-Shot-2019-03-14-at-7-11-09-PM.png)

The only way I'm able to update the port is to change the @port extension, as I guess this also re-instantiates the object. Is there another way of doing this? 

Cheers,
William

**Comment by grrrwaaa** [comment]
You are quite correct, it is not reconnecting on changes to port setting -- I will get an update uploaded shortly.

**Comment by grrrwaaa** [comment]
OK that should be working now (in the devel branch)
